# Generated by Django 2.2.18 on 2021-02-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
