# Generated by Django 2.2.18 on 2021-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='app_notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='file_size',
            field=models.IntegerField(default=5242880),
        ),
    ]
