# Generated by Django 2.2.18 on 2021-02-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rejectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail address'),
        ),
    ]
