# Generated by Django 2.2.18 on 2021-02-23 05:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('due_date', models.DateField(blank=True, default=None, null=True, verbose_name='Date needed by')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Design description')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VersionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.IntegerField(editable=False, verbose_name='Version #')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date uploaded')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.Design')),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, max_length=256, verbose_name='Version Label')),
                ('asset', models.ImageField(upload_to='design_assets', verbose_name='Design Asset')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Date uploaded')),
                ('version_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.VersionGroup')),
            ],
            options={
                'ordering': ['version_label'],
            },
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='design_assets')),
                ('filename', models.CharField(max_length=1000, verbose_name='Original filename')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.Design')),
            ],
        ),
    ]
